# build environment
FROM node:alpine as build
WORKDIR /bitchan
ENV PATH /bitchan/node_modules/.bin:$PATH
COPY package*.json ./
RUN apk add --no-cache git
RUN npm install --global --save
COPY . .
RUN ls /bitchan/src/contracts
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /bitchan/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
