version: '3.7'

services:

  react:
    container_name: react
    build:
      context: ./js
      dockerfile: ./Dockerfile
    volumes:
      - ./js:/bitchan
      - ./solidity/build/contracts:/bitchan/src/contracts
      - node_modules:/bitchan/node_modules
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true
    depends_on:
      - ganache
    restart: on-failure

  solidity:
    image: ethereum/solc:stable
    volumes:
      - ./solidity:/sources 

  truffle:
    build:
      context: ./solidity
      dockerfile: ./Dockerfile.truffle
    working_dir: /sources/solidity
    volumes:
      - ./solidity:/sources 
    depends_on:
      - ganache
    restart: on-failure

  ganache:
    image: trufflesuite/ganache-cli:next
    ports:
      - 9545:8545
    command: >
      ganache-cli \
      --account="0x2264248e750146323373851aec1f3f700f6d9ed0ebdc934137c9e007a047197f,1000000000000000000" \
      --unlock "0x96afb074FBF48A2b12e31D5f1aB2112d7643801B"
    restart: on-failure

volumes:
  node_modules:
