version: '3.7'

services:

  bitchan-dev:
    container_name: bitchan-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./js:/bitchan
      - node_modules:/bitchan/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true

volumes:
  node_modules:  
