version: '3.7'

services:

  bitchan-dev:
    container_name: bitchan-dev
    build:
      context: ./js
      dockerfile: ./Dockerfile
    volumes:
      - ./js/src:/bitchan/src
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    tty: true

volumes:
  node_modules:  
