version: "3.7"

services:
  react-prod:
    container_name: react-prod
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    volumes:
      - ./client:/bitchan
      - ./contracts/build/contracts:/bitchan/src/contracts
      - node_modules_react:/bitchan/node_modules
    ports:
      - 80:80
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - truffle
      - ipfs
    restart: on-failure
    tty: true

  react:
    container_name: react
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/bitchan
      - ./contracts/build/contracts:/bitchan/src/contracts
      - node_modules_react:/bitchan/node_modules
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - truffle
      - ipfs
    restart: on-failure
    tty: true

  solidity:
    image: ethereum/solc:stable
    volumes:
      - ./contracts:/sources

  truffle:
    build:
      context: ./contracts
      dockerfile: ./Dockerfile.truffle
    working_dir: /truffle/contracts
    volumes:
      - ./contracts:/truffle
      - node_modules_truffle:/truffle/node_modules
    depends_on:
      - ganache
    command: truffle deploy
    environment:
      - INFURA_KEY=${INFURA_KEY}
      - MNEMONIC=${MNEMONIC}
      - NODE_OPTIONS=--max_old_space_size=4096
    restart: on-failure

  ganache:
    image: trufflesuite/ganache-cli:next
    ports:
      - 8545:8545
    command: --account="0x2264248e750146323373851aec1f3f700f6d9ed0ebdc934137c9e007a047197f,1000000000000000000" --unlock "0x96afb074FBF48A2b12e31D5f1aB2112d7643801B"
    restart: on-failure

  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfs
    volumes:
      - ./data/ipfs:/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
      - "8081:8081"

volumes:
  node_modules_react:
  node_modules_truffle:
