FROM node:slim

WORKDIR /truffle
ENV PATH /truffle/node_modules/.bin:$PATH

RUN apt-get update && apt-get install -y \
    git \
 && rm -rf /var/lib/apt/lists/*

RUN npm update \
    && npm install truffle -g  --unsafe-perm=true \
    && npm install @truffle/hdwallet-provider
