name: Build and Test Client
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build Contracts
        run: docker-compose build truffle
      - name: Run Test
        run: docker-compose run --rm truffle truffle deploy --network ropsten
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
