name: Build and Test Contracts
on:
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash
    working-directory: client

jobs:
  build:
    name: Build and Test Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build Contracts
        run: docker-compose build truffle
      - name: Run Test
        run: docker-compose run --rm truffle truffle test --stacktrace
